import "../styles/globals.css";
import "../styles/font.css";
import "../styles/pointer.scss";
import "@wevisdemo/ui/styles/typography.css";
import "@wevisdemo/ui/styles/components.css";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <div id="html">
      <Head>
        <title>initiative-process</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://design-systems.wevis.info/typography.css" />
      </Head>
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
